

server: server.cpp
	g++ -o server server.cpp -std=c++11 -I../ -L../lib -lnetwork_static -lpthread -lrt


client: client.cpp
	g++ -o client client.cpp -std=c++11 -I../ -L../lib -lnetwork_static -lpthread -lrt


ddos: ddos.cpp
	g++ -o ddos ddos.cpp -std=c++11 -I../ -L../lib -lnetwork_static -lpthread -lrt

